
import type { Syllabus } from './types';

export const syllabusStructure: Syllabus = {
    "Section A": {
        "General Awareness": {
            "History": ["N/A"], "Polity": ["N/A"], "Constitution": ["N/A"], "Sports": ["N/A"], "Art & Culture": ["N/A"], "Geography": ["N/A"], "Economics": ["N/A"], "Everyday Science": ["N/A"], "Scientific Research": ["N/A"], "National/ International Organizations/ Institutions": ["N/A"], "Current Events": ["N/A"]
        },
        "General Intelligence & Reasoning Ability": {
            "Analogy": ["N/A"], "Classification": ["N/A"], "Series": ["N/A"], "Coding-Decoding": ["N/A"], "Blood Relations": ["N/A"], "Direction Sense Test": ["N/A"], "Logical Venn Diagrams": ["N/A"], "Alphabet Test": ["N/A"], "Sitting Arrangements": ["N/A"], "Mathematical Operations": ["N/A"], "Arithmetical Reasoning": ["N/A"], "Inserting the missing character": ["N/A"], "Number, Ranking and Time Sequence Test": ["N/A"], "Eligibility Test": ["N/A"], "Syllogism": ["N/A"], "Statement and Arguments": ["N/A"], "Statement and Assumptions": ["N/A"], "Statement and Courses of action": ["N/A"], "Statement and Conclusions": ["N/A"], "Deriving Conclusion": ["N/A"], "Assertion and Reason": ["N/A"], "Punch Lines": ["N/A"], "Situation Reaction Tests": ["N/A"], "Cause and Effect": ["N/A"], "Analytical Reasoning": ["N/A"]
        },
        "Arithmetical & Numerical Ability": {
            "Number Systems": ["Simplification", "Decimals", "Fractions", "L.C.M.", "H.C.F."], "Data Interpretation": ["Tables & Graphs", "Pie Chart", "Line Chart", "Line Graph", "Bar Graph", "Venn Diagrams"], "Ratio & Proportion": ["N/A"], "Percentage": ["N/A"], "Average": ["N/A"], "Profit & Loss": ["N/A"], "Discount": ["N/A"], "Simple & Compound Interest": ["N/A"], "Mensuration": ["N/A"], "Time & Work": ["N/A"], "Time & Distance": ["N/A"]
        },
        "English Language & Comprehension": {
            "Parts of speech": ["N/A"], "Tenses": ["N/A"], "Articles & Determiners": ["N/A"], "Subject-Verb Agreement": ["N/A"], "Voice": ["N/A"], "Narration (Direct & Indirect Speech)": ["N/A"], "Sentence Structure": ["N/A"], "Error Detection & Correction": ["N/A"], "Transformation of Sentences": ["N/A"], "Punctuation & Capitalization": ["N/A"], "Modifiers": ["N/A"], "Antonyms": ["N/A"], "Synonyms": ["N/A"], "One-word substitutions": ["N/A"], "Idioms & Phrases": ["N/A"], "Homonyms, Homophones": ["N/A"], "Spelling rules & common errors": ["N/A"], "Word formation (prefix, suffix, root words)": ["N/A"], "Unseen passage": ["N/A"]
        },
        "Hindi Language & Comprehension": {
            "स्वर और व्यंजन": ["N/A"], "संधि (स्वर संधि, व्यंजन संधि, विसर्ग संधि)": ["N/A"], "संधि विच्छेद": ["N/A"], "तत्सम, तद्भव, देशज, विदेशी शब्द": ["N/A"], "पर्यायवाची (Synonyms)": ["N/A"], "विलोम (Antonyms)": ["N/A"], "समश्रुत भिन्नार्थक शब्द (Homonyms)": ["N/A"], "अनेकार्थक शब्द": ["N/A"], "वाक्यांश के लिए एक शब्द (One-word substitution)": ["N/A"], "समास (Compounds)": ["N/A"], "अलंकार": ["N/A"], "रस": ["N/A"], "छंद": ["N/A"], "वाक्य रचना (Sentence Structure)": ["N/A"], "वाक्य भेद (सरल, संयुक्त, मिश्र)": ["N/A"], "वाक्य शुद्धि (Error detection & correction)": ["N/A"], "अशुद्ध वाक्य शुद्ध करना": ["N/A"], "काल और वाच्य": ["N/A"], "लोकोक्तियाँ और मुहावरे": ["N/A"], "अपठित गद्यांश/काव्यांश": ["N/A"], "समझ आधारित प्रश्न (Comprehension)": ["N/A"], "पद-परिचय": ["N/A"], "संधि": ["N/A"], "शब्द शुद्धि और वर्तनी नियम": ["N/A"], "प्रत्यय और उपसर्ग": ["N/A"], "व्याकरण के अंश": ["संज्ञा (लिंग, वचन, कारक)", "सर्वनाम", "विशेषण (विभक्ति, वाचक विशेषण)", "क्रिया (सकर्मक, अकर्मक, सहायक क्रिया, भाववाचक)", "क्रियाविशेषण", "अव्यय", "समुच्चयबोधक, संबंधबोधक, विस्मयादिबोधक"]
        }
    },
    "Section B": {
        "Physics": {
            "EFFECT OF CURRENT": ["Potential; potential difference ohms law", "series combination of resistors, parallel relation combination of resistors", "Power dissipation due to current", "Inter relation between P,V,I and R", "Magnetic field & magnetic lines", "Magnetic field due to current carrying conductor", "Fleming left hand rule, Electromagnetic Induction", "Induced Potential Difference, Induced current", "Direct current, Alternating current", "Frequency of AC, Advantage of Electronic Motor & Electronic Generator"],
            "LIGHT": ["Convergence and Divergence of light", "Images. formed by a Concave Mirror", "related concepts, centre of curvature", "principles axis, optic centre, focus, focal length", "Refraction & laws of refraction", "Images formed by a convex lens", "functioning of vision and remedies", "Applications of spherical mirrors and lenses", "Appreciation of concept of refraction index", "Twinkling of stars", "Dispersion of light", "Scattering of light"],
            "The Human eye and the colourful world": ["Structure of eye", "Defects of eye and their correction"],
            "SOURCES OF ENERGY": ["Different forms of Energy", "Leading to different sources for human use: Fossil Fuels, solar energy", "Biogas", "Wind", "Water and Tidal Energy", "Nuclear Energy", "Renewable versus non-renewable sources"],
            "MOTION: FORCE AND NEWTON'S LAWS": ["Displacement, Velocity, uniform & non-uniform motion", "acceleration distance-time and velocity", "Time graphs for uniform and uniformly accelerated motion", "Equations of motion by graphical method", "Elementary idea of uniform circular motion", "Force and Motion", "Newton's laws of motion Inertia of a body", "Inertia and Mass, Momentum Force and acceleration", "Elementary idea of conservation of momentum, Action and Reaction forces"],
            "GRAVITATION: WORK, ENERGY AND POWER": ["Gravitation", "Universal Law of Gravitation", "Force of gravitation of the earth gravity, acceleration due to gravity", "mass and weight", "free fall", "Work done by a force energy, power", "Kinetic and Potential energy", "law of conservation of energy"],
            "FLOATATION": ["Thrust and Pressure", "Archimedes Principle", "Buoyancy", "Elementary idea of relative density"],
            "SOUND": ["Nature of Sound and its Propagation in various media, Speed of Sound", "Range of hearing in Humans", "Ultra Sound, Reflection of sound", "Echo and SONAR", "Structure of the Human Ear (Auditory aspect only)"]
        },
        "Chemistry": {
            "MATTER-NATURE AND BEHAVIOUR": ["Gases, liquids, solids, plasma and Bose-Enstein condenstate", "types of intermolecular forces", "Classification of matter into mixures and pure substances", "Henry's Law", "Concentration of solutions", "Colloids-phases of colloids, Tyndall effect, Brownian movement", "Suspension", "Properties of matter", "Measurement of properties of matter-S.I. system of units", "physical and chemical changes", "Laws of chemical combination Gay Lussac's law, Avogadro law", "atomic and molecular masses, average atomic. mass, mole concept and molar masses, percentage compostion"],
            "STRUCTURE OF ATOM": ["Dalton's atomic theory, Discharge tube experiments", "J.J. Thomson's model of atom, Rutherford's model, Bohr's model of atom", "electronic configuration, formation of ions", "Characterisation of elements as metals, metalloids, or nonmetals", "isotopes (their applications), isobars and isotones"],
            "PERIODIC CLASSIFICATION OF ELEMENTS": ["Mendeleev's periodic law", "Periodic properties of elements, trends in the periods and groups", "Improtance of the periodic table, position of hydrogen in the periodic table"],
            "CHEMICAL SUBSTANCES": ["Nature and behaviour Acid, Basis and Salts", "Classical definition of acids and bases, Bronsted-Lowry theory, Lewis conceipt of acid and bases", "relative.strengths of acids and bases, logarithmic or p scale-pH,pOH and pkw, ionic equilibria in a solution", "Action of indicators on acids and bases, sources of acid and bases", "SaltClassification of salts and their pH"],
            "CHEMICAL REACTIONS": ["Formulation of chemical equations, balancing chemical equations", "Types of chemical equations with examples"],
            "METALS AND NON-METALS": ["Characters of metals and non-metals including all properties and applications", "Occurrence of metals in nature: ores and minerals, enrichment of ores metallurgical operations", "Corrosion: rusting of iron - prevention of corrosion"],
            "CARBON COMPOUNDS": ["Position of carbon in the periodic table", "Concept of hybridization and shapes of molecules structural formula and molecular models", "types of reactions undergone by organic compounds, homologous series of compounds having different functional groups, isomerism, IUPAC nomenclature of organic compounds", "Hydrocarbons - their classification formation of coal and petroleum", "Industrial source, preparation and properties of alkanes", "Alcohols: Preparation and properties", "Qualitative analysis of alcohols, iodoform test, effect of alcohols on living beings", "Carboxylic acids: Preparation and properties", "Functional group analysís of carboxylic acid", "Soaps, detergents, biodegradable detergents", "Carbon fibres"],
            "MAN MADE MATERIAL": ["Ceramics, cement, porcelain, glass, carbon fibres, soaps and detergents, polymers, fibres 'and plastics"]
        },
        "Biology": {
            "Life Processes": ["What are life Processes", "Need for Nutrition", "Different modes of. Nutrition in animals", "What is Photosynthesis", "Various steps of holozoic nutrition", "Aerobic and anaerobic respiration", "Transportation in Human beings", "Transportation in Plants", "Transportation in animals", "Excretion in animals including Human beings", "Excretion in Plants"],
            "Control & Co-Ordination": ["Animals - nervous system", "Basic unit of Nervous System in animals", "Reflex action", "Human Brain", "Co-Ordination in plants", "Geotropism - Positive, Negative", "Hormones in animals", "Endocrine & Exocrine glands"],
            "Reproduction": ["Importance of variation", "Modes of Reproduction used by single organisms", "Sexual Reproduction in plants and animals", "Reproduction in Human beings", "What happens when egg is not fertilised", "Modes of avoiding pregnancy (family planning)"],
            "Heredity and Evolution": ["What is heredity?", "Medals Law of inheritance", "How is sex determined?", "Evolution & Classification", "Acquired and inherited traits", "Homologus and Analogous organs", "What are fossils?", "Human Evolution"],
            "Natural resources": ["The fundamental unit of Life", "What are living organisms made of?", "Structure organization of cell"],
            "Tissues": ["Define tissue", "Types of plants tissue and animals tissues"],
            "Diversity of living organisms": ["Basis of Classification", "Classification & Evolution", "Hierarchy of classification - - groups", "Plantae, Animalia", "Nomenclature"],
            "Why do we fall ill": ["Health & its failure", "Diseases and their causes", "Types of diseases- Infectious, Noninfectious", "Prevention of diseases Smmunisation"],
            "OUR ENVIRONMENT": ["Atmosphere, roll of atmosphere in climate control, wind, rain", "environmental pollution: Global warming and green house effect, acid rain, particulate pollutants, smog, formation of photochemical smog", "Formation of ozone and its break down ozone hole, causes of ozone hole formation, polar vortex, effects of depletion of ozone hole", "Water pollution-oxygen demand, chemical oxygen demand, internationalstandard of drinking water, processing of drinking water", "Soil pollution: water recycling, strategies to control environmental pollution, itscollection and proper methods of disposal", "Biogeochemical cycles: water cycle, nitrogen cycle, carbon cycle and oxygencycle"],
            "CONSERVATION OF NATURAL RESOURCES": ["Pollution of river water, Ganga action plan for improving quality of water", "Need for sustainable management of natural resources", "Development of non- conventional energy resources to prevent pollution and atmospheric conservation"],
            "Improvement in Food Resources": ["Improvement in crop yield", "Animal Husbandry", "Need for intercropping", "Cross Breeding"],
            "Bone and Cartilage": ["Structure and types of bones and cartilages, Ossification, bone growth and resorption"],
            "Animal Diversity": ["Kingdom Protista, Amphibia, Reptiles, Aves, Mammals", "Phylüm Porifera, Phylum Cnidaria, Phylüm Annelida, Phylum Arthròpoda, Phylum Mollusca"],
            "Comparative Anatomy and Developmental Biology of Vertebrates": ["Integumentary System", "Skeletal System", "Digestive System", "Respiratory System", "Circulatory System", "Urinogenital System", "Nervous system", "Sense Organ", "Early Embryonoic Development", "Late Embryonic Development", "Control of Development"],
            "Physiology and Biochemistry": ["Nerve and Muscle", "Digestion", "Respiration", "Excretion", "Cardiovascular System", "Reproduction and Endocrine Glands", "Carbohydrate Metabolism", "Lipid Metabolism", "Protein Metabolism", "Enzymes", "Extinction", "Macro-evolution"],
            "Applied Zoology": ["Introduction to Host-parasite Relationship", "Epidemiology of Diseases,Rickettsiaeand Spirochaetes", "Parasitic Protozoa", "Parasitic Helminthes", "Insects of Eco Importance,Insects of Medical Importance", "Animal Husbandry", "Poultry Farming", "Fish Technology"],
            "Aquatic Biology": ["Aquatic Biomes", "Freshwater Biology", "Marine Biology", "Management of Aquatic Resources"],
            "Immunology": ["Overview of the Immune System", "Cells and Organs of the Immune System", "Antigens", "Antibodies", "Working of the immune system", "Immune system in health and disease", "Vaccines"],
            "Reproductive Biology": ["Reproductive Endocrinology", "Functional anatomy of male reproduction", "Functional anatomy of female reproduction", "Reproductive Health"],
            "Insect, Vectors and Diseases": ["Introduction of Insects", "Concept of Vectors", "Insects as Vectors", "Dipteran as Disease Vectors", "Siphonaptera as disease vectors", "Hempitera as Disease Vectors"],
            "Sericulture": ["Introduction", "Biology of Silkworm", "Rearing of Silkworms", "Pests and Diseases"]
        }
    }
};
